name: flutter_face_authenticator_sample
description: Sample of CAF Face Authenticator SDK
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  caf_face_authenticator:
    git:
      url: https://github.com/combateafraude/flutter-faceauth-sdk
      rev: 0.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
